Description: Allows central management of computing instances; building on essentials
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  MaintenanceWindow:
    Description: 'Acceptable outage intervals for Systems Manager changes'
    Type: String
    Default: 'Weekly-0400SundayUTC-7'
Resources:
  ComputingInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: "/"
      Roles:
        - !Ref ComputingInstanceRole
  ComputingInstanceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      Path: '/'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - 'ec2.amazonaws.com'
          Action:
            - 'sts:AssumeRole'
      ManagedPolicyArns:
            - 'arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore'
Outputs:
  ComputingInstanceProfile:
    Description: Profile to allow instances to adopt roles and interact with services
    Value: !Ref ComputingInstanceProfile
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-ComputingInstanceProfile'
  ComputingInstanceRole:
    Description: Role to allow instances tag and receive management via Systems Manager
    Value: !Ref ComputingInstanceRole
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-ComputingInstanceRole'
  MaintenanceWindow:
    Value: !Ref MaintenanceWindow
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-MaintenanceWindow'
