AWSTemplateFormatVersion: '2010-09-09'

Resources:
  PasswordPolicy:
    Type: Community::IAM::PasswordPolicy
    Properties:
      MinimumPasswordLength: 18
      RequireLowercaseCharacters: true
      RequireNumbers: true
      RequireSymbols: true
      RequireUppercaseCharacters: true
      AllowUsersToChangePassword: false
